StartupEvents.registry('fluid', event => {

event.create('ammo_reservation_potion')
    .displayName('Ammo reservation Potion')
    .noBlock()
    .noBucket()
    .stillTexture('minecraft:block/sand')
    .flowingTexture('minecraft:block/sand')
event.create('archery_potion')
    .displayName('Archery Potion')
    .noBucket()
    .noBlock()
event.create('battle_potion')
    .tint(0x7A5AB3)
    .displayName('battle_potion')
    .noBucket()
    .noBlock()
event.create('biome_sight_potion')
    .tint(0xF6A0C6)
    .displayName('Biome Sight Potion')
    .noBucket()
    .noBlock()
event.create('builder_potion')
    .tint(0x6B4836)
    .displayName('Builder Potion')
    .noBucket()
    .noBlock()
event.create('calming_potion')
    .tint(0x4745C9)
    .displayName('Calming Potion')
    .noBucket()
    .noBlock()
event.create('crate_potion')
    .tint(0x935D28)
    .displayName('Crate Potion')
    .noBucket()
    .noBlock()
event.create('dangersense_potion')
    .tint(0xA2381A)
    .displayName('Dangersense Potion')
    .noBucket()
    .noBlock()
event.create('endurance_potion')
    .tint(0x898A86)
    .displayName('Endurance Potion')
    .noBucket()
    .noBlock()
event.create('fishing_potion')
    .tint(0x208548)
    .displayName('Fishing Potion')
    .noBucket()
    .noBlock()
event.create('flipper_potion')
    .tint(0x0C5785)
    .displayName('Flipper Potion')
    .noBucket()
    .noBlock()
event.create('gravitation_potion')
    .tint(0x7714E8)
    .displayName('Gravitation Potion')
    .noBucket()
    .noBlock()
event.create('greater_luck_potion')
    .tint(0xD71CB0)
    .displayName('Greater Luck Potion')
    .noBucket()
    .noBlock()
event.create('heartreach_potion')
    .tint(0xC91F97)
    .displayName('Heartreach Potion')
    .noBucket()
    .noBlock()
event.create('hunter_potion')
    .tint(0xCE5D11)
    .displayName('Hunter Potion')
    .noBucket()
    .noBlock()
event.create('inferno_potion')
    .tint(0xFFA403)
    .displayName('Inferno Potion')
    .noBucket()
    .noBlock()
event.create('ironskin_potion')
    .tint(0xBDB938)
    .displayName('Ironskin Potion')
    .noBucket()
    .noBlock()
event.create('lesser_luck_potion')
    .tint(0x899AC2)
    .displayName('Lesser Luck Potion')
    .noBucket()
    .noBlock()
event.create('lifeforce_potion')
    .tint(0x8E0A00)
    .displayName('Lifeforce Potion')
    .noBucket()
    .noBlock()
event.create('luck_potion')
    .tint(0x252A3B)
    .displayName('Luck Potion')
    .noBucket()
    .noBlock()
event.create('magic_power_potion')
    .tint(0x5d1eb2)
    .displayName('magic_power_potion')
    .noBucket()
    .noBlock()
event.create('mana_regeneration_potion')
    .tint(0xf5229e)
    .displayName('Mana regeneration Potion')
    .noBucket()
    .noBlock()
event.create('mining_potion')
    .tint(0x528487)
    .displayName('Mining Potion')
    .noBucket()
    .noBlock()
event.create('night_owl_potion')
    .tint(0x63920f)
    .displayName('Night Owl Potion')
    .noBucket()
    .noBlock()
event.create('obsidian_skin_potion')
    .tint(0x4a3c83)
    .displayName('Obsidian Skin Potion')
    .noBucket()
    .noBlock()
event.create('rage_potion')
    .tint(0xc77703)
    .displayName('Rage Potion')
    .noBucket()
    .noBlock()
event.create('shine_potion')
    .tint(0xc3c916)
    .displayName('Shine Potion')
    .noBucket()
    .noBlock()
event.create('sonar_potion')
    .tint(0x4e7c0a)
    .displayName('Sonar Potion')
    .noBucket()
    .noBlock()
event.create('spelunker_potion')
    .tint(0xf9d74c)
    .displayName('Spelunker Potion')
    .noBucket()
    .noBlock()
event.create('summoning_potion')
    .tint(0x6e811a)
    .displayName('Summoning Potion')
    .noBucket()
    .noBlock()
event.create('thorns_potion')
    .tint(0x8aa911)
    .displayName('Thorns Potion')
    .noBucket()
    .noBlock()
event.create('titan_potion')
    .tint(0x60b232)
    .displayName('Titan Potion')
    .noBucket()
    .noBlock()
event.create('water_walking_potion')
    .tint(0x1f74e7)
    .displayName('Water Walking Potion')
    .noBucket()
    .noBlock()
event.create('wrath_potion')
    .tint(0x872b24)
    .displayName('Wrath Potion')
    .noBucket()
    .noBlock()


event.create('venom')
    .tint(0x872b24)
    .displayName('Venom')
    .noBucket()
    .noBlock()
})